---
- name: install pakcages and deploy ssh
  hosts: apache2.projet.intranet
  become: yes
  become_method: sudo
  vars:
    ports:
      - '80'
      - '443'
      - '8080'
  roles:
    - stage-2
    
